version: "2.2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOO_MY_ID=1
      - "TZ=Asia/Shanghai"
    volumes:
      - /data/kafka/data/zookeeper/data:/data
      - /data/kafka/data/zookeeper/log:/datalog

  kafka:
    image: wurstmeister/kafka:2.11-1.0.2
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      - "TZ=Asia/Shanghai"
      - KAFKA_LOG_RETENTION_HOURS=1440
      - KAFKA_LOG_DIRS=/kafka/KafkaLog
      - KAFKA_ZOOKEEPER_CONNECT=internal_ip_address:2181
      - KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://external_ip_address:9092
      - KAFKA_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_SECURITY_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.auth.SimpleAclAuthorizer
      - KAFKA_SUPER_USERS=User:admin;User:user1
      - KAFKA_OPTS=-Djava.security.auth.login.config=/opt/kafka/config/kafka_plain_jaas.conf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/kafka/KafkaLog:/kafka/KafkaLog
      - /data/kafka/config/kafka_plain_jaas.conf:/opt/kafka/config/kafka_plain_jaas.conf
      - /data/kafka/config/consumer.properties:/opt/kafka/config/consumer.properties
      - /data/kafka/config/producer.properties:/opt/kafka/config/producer.properties
